config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  resources :transaract_groups
  resources :groups, only: [:index, :create, :new, :destroy] do
  resources :transaracts
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :manage, :all
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/group.rb
class Group < ApplicationRecord
  # Define associations.
  belongs_to :author, class_name: 'User'
  has_many :transaract_groups
  has_many :transaracts, through: :transaract_groups

  validates :icon, :name, presence: true
end

app/models/transaract.rb
class Transaract < ApplicationRecord
  # Define associations.
  has_many :transaract_groups
  has_many :groups, through: :transaract_groups
  belongs_to :author, class_name: 'User'

  validates :name, :author_id, presence: true
  validates :amount, numericality: true
end

app/models/transaract_group.rb
class TransaractGroup < ApplicationRecord
  belongs_to :transaract
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Define associations.
  has_many :transaracts
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :name) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @categories = Group.where(author: current_user)
    @transaracts = Transaract.where(author: current_user)
    @transaract_groups = TransaractGroup.all
  end

  def new
    @new_category = Group.new
  end

  def create
    @create_category = Group.create(create_category_params)
    if @create_category.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def create_category_params
    params.permit(:name, :icon, :author_id)
  end
end

app/controllers/transaract_groups_controller.rb
class TransaractGroupsController < ApplicationController
  def index; end
end

app/controllers/transaracts_controller.rb
class TransaractsController < ApplicationController
  def index
    @groups = Group.find_by(id: params[:group_id])
    @transaracts = TransaractGroup.includes(:transaract).where(group: @groups).order(created_at: :desc)
    @total_transactions = @transaracts.map { |transaction| transaction.transaract.amount }.sum
  end

  def new
    @new_transaract = Transaract.new
    @groups = Group.where(author: current_user)
  end

  def create
    @create_transaract = Transaract.create(name: params[:name], amount: params[:amount], author: current_user)
    if @create_transaract
      @new_transaract_group = TransaractGroup.create(transaract_id: @create_transaract.id, group_id: params[:group_id])
      redirect_to groups_path
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      redirect_to groups_path
    else
      render 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Use the Controller#Action to determine the current page
  def nav_bar_content(controller_name, action_name)
    case "#{controller_name}##{action_name}"
    when 'groups#index'
      'Categories'
    when 'transaracts#index'
      'Transaracts'
    when 'devise/sessions#new'
      'Login'
    when 'devise/registrations#new'
      'Register'
    when 'groups#new' && 'transaracts#new'
      'details'
    else
      ''
    end
  end
end

app/views/groups/index.html.erb
<%= render partial: 'shared/navbar' %>
<main class="container-fluid main-container">
<div class="groups_container">
<% @categories.each do |category| %>
  <div class="container-fluid catergory-card">
  <%= image_tag category.icon  %>
  <div class= "name_date">
  <h3><%=link_to category.name, group_transaracts_path(category.id)%></h3>
  <p>
  <%= category.created_at.strftime("%B %d %Y") %>
</p>
</div>
  <% total_price = 0 %>
  <% @transaract_groups.each do |group| %>
    <% if group.group_id == category.id %>
    <% total_price += group.transaract.amount %> 
    <% end %>
    <% end %>
  <p>$<%= total_price %></></p>
  </div>
<% end %>
</div>
<div class="btn_container">
<%= link_to "Add new category", new_group_path, class:"btn_size" %>
</div>
</main>

app/views/groups/new.html.erb
<%= render partial: 'shared/details_nav' %>
<div class="container form_styles">
<h1> Create a new category</h1>

<%= form_with model: @group, url: groups_path do |f| %>
  <div>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :icon %><br />
  <%= f.text_field :icon %>
  </div>
  <%= f.hidden_field :author_id, value: current_user.id %>
  <%= f.submit :submit %><br />
  <% end %>
</div>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsCapstoneProjectBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.lineicons.com/4.0/lineicons.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "category", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "forms", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="flash_messages">
  <%= render partial: "shared/flash" %>
  </div>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_details_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-primary p-3" style="background-color: #3778c2;">
<div class="container-fluid">
<%= link_to groups_path do %>
  <i class="lni lni-arrow-left text-light search"></i>
<% end %>
<h5 class="text-light"><%= nav_bar_content(params[:controller], params[:action])%></h5>
<span class="text-light"></span>
</div>
</nav>  

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert]%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-primary p-3" style="background-color: #3778c2;">
<div class="container-fluid">
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
<span><i class="lni lni-menu text-light"></i></span>
</button>
<h2 class="text-light"><%= nav_bar_content(params[:controller], params[:action])%></h2>
<span><i class="lni lni-search-alt text-light search"></i></span>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <%= link_to "Home", root_path, class:"nav-link active text-light", aria_current:"page" %>
    </li>
  </ul>
  <% if user_signed_in? %>
<span class="nav-text text-light mx-3"><%= link_to current_user.name, edit_user_registration_path, class:"nav-link" %></span>
  <span>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-light" %>
  <% end %>
  </span>

</div>
</div>
</nav>  

app/views/transaract_groups/index.html.erb
<h1> Welcome to the transaract_groups index page</h1>

app/views/transaracts/index.html.erb
<%= render partial: 'shared/navbar' %>
<section class="container-fluid main-container">
<div class="container-fluid transaract-card">
<h3>Total Amount: $<%= @total_transactions %></h3>
</div>
<div class="container transaracts_container">
<% @transaracts.each do |transaract| %>
  <div class="container-fluid catergory-card">
  <%= image_tag "https://cdn-icons-png.flaticon.com/128/9080/9080379.png", size: 8*10 %>
  <h3><%= transaract.transaract.name %></h3>
  <p>$<%= transaract.transaract.amount %></p>
  </div>
  <% end %>
  </div>
  <div class="btn_container">
  <%= link_to "Add Transaract", new_group_transaract_path, class:"btn_size" %>
  </div>
  </section>

app/views/transaracts/new.html.erb
<%= render partial: "shared/details_nav" %>
<div class="container form_styles">
<%= form_with model: @transaract, url: group_transaracts_path do |f|%> 
  <div>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :amount %><br />
  <%= f.number_field :amount %>
  </div>
  
  <div> 
  <%= f.label :category %><br />
  <%= f.select(:group_id, @groups.map{|u| [u.name]}, {:include_blank => 'Choose a category', :disabled => 1}) %>
  </div>
  
  <%= f.submit %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container mx-auto splash">
<h1> TransaRacts </h1>
<span class="container buttons">
<%= link_to "Log In", new_user_session_path, class:"btn btn-primary" %>
<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-light" %>
</span>
</div>